version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 33060:3306
    volumes:
     - db:/var/lib/mysql    
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 49160:8080  
    stdin_open: true
    tty: true

volumes:
  db: